### ISSUE TITLE
Allowing Admin Control to be applied to admins using custom admin flags.

### ISSUE THREAD

**Issue by MSX-98** [TiBarification/Jail-Warden-Pro#90]
Hi there.

Firstly, I'd like to say thank you for creating such a useful and customisable plugin. This plugin has covered every single aspect that I required in my new JB server, and more. I appreciate the amount of time this must have taken you.

I am having a small issue where I can't get the "Wardening" sub-category within SM's Admin Menu to appear unless I am a root admin (with flag Z, B flag or any other flags don't seem to work). Upon further inspection in admincontrol.sp, I found that admins with the ban flag should be able to use this, but this simply is not working for some reason, even when its changed to slay, for example. 

I was hoping this could be changed to allow the server operator to change which flag will allow this menu to show up though some sort of server convar maybe?

I have admin groups set up and I cannot find specific commands for these to add them individually, so I assume it is all done via scripts.

I apologise for my lack of knowledge when it comes to SourcePawn, I am new to CS:S Server modding (sourcemod-supported games as a whole tbh) and I am fairly unfamilar with the language. I am much more used to LUA for Gmod and FiveM from servers I used to run in the past.

I would love to support this project if at all possible so if any information on how I can do this, will also be greatly appreciated.

Thank you and good day :)

**Comment by TiBarification** [comment]
Refering to [AddToTopMenu docs](https://sm.alliedmods.net/new-api/topmenus/AddToTopMenu) access by cmdname can be overriden in admin_overrides.cfg or similar config. Try to specify it directly in overrides. The name is: "jwp_admincontrol".
https://wiki.alliedmods.net/Overriding_Command_Access_(Sourcemod). Or try to rename it to "sm_ban" for example or any registered command. I think there can be an issue because I do not used command name. If it will work, I will change it, right now don't have ability to test it.

**Comment by MSX-98** [comment]
> jwp_admincontrol

Yep, the override method worked. I was unaware this was even a thing. I could definately streamline my admin groups a lot better with this knowledge in mind.

I did try renaming the command to a few different variations already but it didn't seem to make a difference. The override method works perfectly fine so its not really an issue anymore, if others were having a similar issue.

Thanks for the help mate!
